Models/Fellow.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HiMVC.Models
{
    /// <summary>
    /// 小夥伴基本資訊
    /// </summary>
    public class Fellow
    {
        [DisplayName("唉低")]
        public int Id { get; set; }

        [DisplayName("姓名")]
        [Required]
        public string Name { get; set; }
    }
}

Controllers/FellowsController.cs
using HiMVC.Models;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HiMVC.Controllers
{
    public class FellowsController : Controller
    {
        private readonly AppDbContext db = new AppDbContext();

        /// <summary>
        /// [GET] 小夥伴列表
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Index()
        {
            return View(await db.Fellows.ToListAsync());
        }

        /// <summary>
        /// [GET] 小夥伴詳情
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fellow = await db.Fellows.FindAsync(id);
            if (fellow == null)
            {
                return HttpNotFound();
            }
            return View(fellow);
        }

        /// <summary>
        /// [GET] 新增小夥伴
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// [POST] 新增小夥伴
        /// </summary>
        /// <param name="restaurant"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name")] Fellow fellow)
        {
            if (ModelState.IsValid)
            {
                db.Fellows.Add(fellow);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(fellow);
        }

        /// <summary>
        /// [GET] 修改小夥伴
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fellow = await db.Fellows.FindAsync(id);
            if (fellow == null)
            {
                return HttpNotFound();
            }
            return View(fellow);
        }

        /// <summary>
        /// [POST] 修改小夥伴
        /// </summary>
        /// <param name="restaurant"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] Fellow fellow)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fellow).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(fellow);
        }

        /// <summary>
        /// [GET] 刪除小夥伴
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fellow = await db.Fellows.FindAsync(id);
            if (fellow == null)
            {
                return HttpNotFound();
            }
            return View(fellow);
        }

        /// <summary>
        /// [POST] 刪除小夥伴
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var fellow = await db.Fellows.FindAsync(id);
            if (fellow == null)
            {
                return HttpNotFound();
            }
            db.Fellows.Remove(fellow);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Fellows/Create.cshtml
@model HiMVC.Models.Fellow

@{
    ViewBag.Title = "新增小夥伴";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增啦，哪次不新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回頭是岸", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Fellows/Delete.cshtml
@model HiMVC.Models.Fellow

@{
    ViewBag.Title = "拋棄小夥伴";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="拋棄啦，哪次不拋棄" class="btn btn-default" /> |
            @Html.ActionLink("回頭是岸", "Index")
        </div>
    }
</div>

Views/Fellows/Details.cshtml
@model HiMVC.Models.Fellow

@{
    ViewBag.Title = "小夥伴詳情";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("回頭是岸", "Index")
</p>

Views/Fellows/Edit.cshtml
@model HiMVC.Models.Fellow

@{
    ViewBag.Title = "編輯小夥伴";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存啦，哪次不儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回頭是岸", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Fellows/Index.cshtml
@model IEnumerable<HiMVC.Models.Fellow>

@{
    ViewBag.Title = "小夥伴列表";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("新增小夥伴", "Create", "Fellows", new { @class = "btn btn-primary" })
</p>
@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("詳情", "Details", new { id = item.Id }) |
                    @Html.ActionLink("刪除", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
}
else
{
    <h3>查無資料</h3>
}