Models/Restaurant.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace HiMVC.Models
{
    /// <summary>
    /// 食堂基本資訊
    /// </summary>
    public class Restaurant
    {
        [DisplayName("唉低")]
        public int Id { get; set; }

        [DisplayName("名稱")]
        [Required]
        public string Name { get; set; }

        [DisplayName("地址")]
        public string Address { get; set; }

        [DisplayName("電話")]
        public string PhoneNumber { get; set; }

        [DisplayName("星數")]
        [Range(0, 5)]
        public double? Stars { get; set; }

        [DisplayName("評價數")]
        [Range(0, double.PositiveInfinity)]
        public int? Comments { get; set; }

        [DisplayName("標籤")]
        public string Tags { get; set; }

        [DisplayName("類別")]
        [Required]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        [NotMapped]
        public List<string> TagsList
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Tags))
                {
                    return new List<string>();
                }
                return Tags?.Split(',').ToList();
            }
            set
            {
                if (value?.Count > 0)
                {
                    Tags = string.Join(",", value) + ",";
                }
                else
                {
                    Tags = string.Empty;
                }
            }
        }
    }
}

Models/Review.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HiMVC.Models
{
    /// <summary>
    /// 評價
    /// </summary>
    public class Review
    {
        [DisplayName("唉低")]
        public int Id { get; set; }

        [DisplayName("小夥伴")]
        [Required]
        public int FellowId { get; set; }

        [DisplayName("食堂")]
        [Required]
        public int RestaurantId { get; set; }

        [DisplayName("星數")]
        [Range(0, 5)]
        public double? Stars { get; set; }

        [DisplayName("評價")]

        public string Comment { get; set; }

        [DisplayName("小夥伴")]
        public virtual Fellow Fellow { get; set; }

        [DisplayName("食堂")]
        public virtual Restaurant Restaurant { get; set; }
    }
}

ViewModels/RestaurantViewModel.cs
using HiMVC.Models;
using System.Collections.Generic;
using System.ComponentModel;

namespace HiMVC.ViewModels
{
    public class RestaurantQueryModel : Pagination
    {
        [DisplayName("名稱")]
        public string Name { get; set; }

        [DisplayName("類別")]
        public string CategoryName { get; set; }

        [DisplayName("地址")]
        public string Address { get; set; }

        [DisplayName("電話")]
        public string PhoneNumber { get; set; }

        [DisplayName("星數")]
        public RangeValues<float?> Stars { get; set; }

        [DisplayName("評價數")]
        public RangeValues<int?> Comments { get; set; }

        [DisplayName("標籤")]
        public string Tags { get; set; }
    }

    public class RestaurantViewModel : RestaurantQueryModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
    }
}

Controllers/RestaurantsController.cs
using HiMVC.Models;
using HiMVC.ViewModels;
using LinqKit;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HiMVC.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly AppDbContext db = new AppDbContext();

        /// <summary>
        /// [GET] 食堂列表
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Index(RestaurantViewModel restaurantViewModel)
        {
            var query = db.Restaurants.Include(x => x.Category).AsQueryable();
            if (!string.IsNullOrWhiteSpace(restaurantViewModel.Name))
            {
                query = query.Where(x => x.Name.Contains(restaurantViewModel.Name));
            }
            if (!string.IsNullOrWhiteSpace(restaurantViewModel.Address))
            {
                query = query.Where(x => x.Address.Contains(restaurantViewModel.Address));
            }
            if (!string.IsNullOrWhiteSpace(restaurantViewModel.PhoneNumber))
            {
                query = query.Where(x => x.PhoneNumber.Contains(restaurantViewModel.PhoneNumber));
            }
            if (restaurantViewModel.Stars?.Start > 0)
            {
                query = query.Where(x => x.Stars >= restaurantViewModel.Stars.Start);
            }
            if (restaurantViewModel.Stars?.End > 0)
            {
                query = query.Where(x => x.Stars <= restaurantViewModel.Stars.End);
            }
            if (restaurantViewModel.Comments?.Start > 0)
            {
                query = query.Where(x => x.Comments >= restaurantViewModel.Comments.Start);
            }
            if (restaurantViewModel.Comments?.End > 0)
            {
                query = query.Where(x => x.Comments <= restaurantViewModel.Comments.End);
            }
            if (!string.IsNullOrWhiteSpace(restaurantViewModel.Tags))
            {
                var tagQuery = PredicateBuilder.New<Restaurant>(false);
                var tags = restaurantViewModel.Tags.Split(',');
                foreach (var tag in tags)
                {
                    tagQuery = tagQuery.Or(x => x.Tags.Contains(tag + ","));
                }
                query = query.Where(tagQuery);
            }
            restaurantViewModel.Restaurants = await query
                .OrderByDescending(x => x.Id)
                .Skip((restaurantViewModel.Page.Value - 1) * restaurantViewModel.Size.Value)
                .Take(restaurantViewModel.Size.Value)
                .ToListAsync();
            var total = await query.CountAsync();
            restaurantViewModel.Total = total;
            return View(restaurantViewModel);
        }

        /// <summary>
        /// [GET] 食堂詳情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var restaurant = await db.Restaurants.FindAsync(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        /// <summary>
        /// [GET] 新增食堂
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        /// <summary>
        /// [POST] 新增食堂
        /// </summary>
        /// <param name="restaurant"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Name,Address,PhoneNumber,Tags,CategoryId")] Restaurant restaurant
        )
        {
            if (ModelState.IsValid)
            {
                db.Restaurants.Add(restaurant);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", restaurant.CategoryId);
            return View(restaurant);
        }

        /// <summary>
        /// [GET] 修改食堂
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var restaurant = await db.Restaurants.FindAsync(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", restaurant.CategoryId);
            return View(restaurant);
        }

        /// <summary>
        /// [POST] 修改食堂
        /// </summary>
        /// <param name="restaurant"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Exclude = "Stars,Comments")] Restaurant restaurant
        )
        {
            if (ModelState.IsValid)
            {
                var target = await db.Restaurants.FindAsync(restaurant.Id);
                if (restaurant == null)
                {
                    return HttpNotFound();
                }
                target.Name = restaurant.Name;
                target.Address = restaurant.Address;
                target.PhoneNumber = restaurant.PhoneNumber;
                target.Tags = restaurant.Tags;
                target.CategoryId = restaurant.CategoryId;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", restaurant.CategoryId);
            return View(restaurant);
        }

        /// <summary>
        /// [GET] 刪除食堂
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var restaurant = await db.Restaurants.FindAsync(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        /// <summary>
        /// [POST] 刪除食堂
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var restaurant = await db.Restaurants.FindAsync(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            db.Restaurants.Remove(restaurant);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// [GET] 評價食堂
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Review(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var restaurant = await db.Restaurants.FindAsync(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            var reviewViewModel = new ReviewViewModel { Restaurant = restaurant };
            return View(reviewViewModel);
        }

        /// <summary>
        /// [POST] 評價食堂
        /// </summary>
        /// <param name="reviewViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Review(ReviewViewModel reviewViewModel)
        {
            var restaurant = await db.Restaurants.FindAsync(reviewViewModel.Review.RestaurantId);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            var fellow = await db.Fellows.FirstOrDefaultAsync(
                x => x.Name == reviewViewModel.Review.Fellow.Name
            );
            if (fellow == null)
            {
                fellow = db.Fellows.Add(reviewViewModel.Review.Fellow);
                await db.SaveChangesAsync();
            }
            var hasReviewed =
                await db.Reviews
                    .Where(x => x.RestaurantId == reviewViewModel.Review.RestaurantId)
                    .Where(x => x.FellowId == fellow.Id)
                    .CountAsync() > 0;
            ViewBag.HasReviewed = hasReviewed;
            if (!hasReviewed)
            {
                reviewViewModel.Review.Fellow = fellow;
                db.Reviews.Add(reviewViewModel.Review);
                await db.SaveChangesAsync();
                restaurant.Stars = await db.Reviews
                    .Where(x => x.RestaurantId == restaurant.Id)
                    .Where(x => x.Stars != null)
                    .AverageAsync(x => x.Stars);
                restaurant.Stars = Math.Round(restaurant.Stars.Value, 1);
                restaurant.Comments = await db.Reviews
                    .Where(x => x.RestaurantId == restaurant.Id)
                    .Where(x => x.Comment != null)
                    .CountAsync();
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            reviewViewModel.Restaurant = restaurant;
            return View(reviewViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();

Views/Restaurants/Create.cshtml
@model HiMVC.Models.Restaurant

@{
    ViewBag.Title = "新增食堂";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, "請選擇", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增啦，哪次不新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回頭是岸", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Restaurants/Delete.cshtml
@model HiMVC.Models.Restaurant

@{
    ViewBag.Title = "刪除食堂";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stars)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="拋棄啦，哪次不拋棄" class="btn btn-default" /> |
            @Html.ActionLink("回頭是岸", "Index")
        </div>
    }
</div>

Views/Restaurants/Details.cshtml
@model HiMVC.Models.Restaurant

@{
    ViewBag.Title = "食堂詳情";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stars)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("回頭是岸", "Index")
</p>

Views/Restaurants/Edit.cshtml
@model HiMVC.Models.Restaurant

@{
    ViewBag.Title = "編輯食堂";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, null, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, "請選擇", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存啦，哪次不儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回頭是岸", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Restaurants/Index.cshtml
@using HiMVC.Helpers
@model HiMVC.ViewModels.RestaurantViewModel

@{
    ViewBag.Title = "食堂列表";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("新增食堂", "Create", "Restaurants", new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm(null, null, FormMethod.Get))
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="瞅瞅" class="btn btn-primary" />
                @Html.EditorFor(model => model.Page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
}

<hr />

@if (Model.Restaurants.Count() > 0)
{
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stars)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comments)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tags)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.Restaurants)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stars)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comments)
                </td>
                <td>
                    @foreach (var tag in item.TagsList)
                    {
                        <span class="badge">@tag</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("詳情", "Details", new { id = item.Id }) |
                    @Html.ActionLink("刪除", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("評價", "Review", new { id = item.Id })
                </td>
            </tr>
        }
    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="@Shared.GetClassNames(
                "page-item",
                Model.IsFirst ? "disabled" : "",
                Model.IsFirst ? "foo" : "")">
                <a class="page-link" href="@Shared.GetPagingUrl(1)">&lt;&lt;</a>
            </li>
            <li class="page-item@(Model.IsFirst ? " disabled" : "")">
                <a class="page-link" href="@Shared.GetPagingUrl(Model.Page.Value - 1)">&lt;</a>
            </li>
            @foreach (var item in Model.GetPageItems())
            {
                <li class="page-item@(item.IsCurrent ? " active" : "")">
                    <a class="page-link" href="@Shared.GetPagingUrl(item.Page)">@item.Page</a>
                </li>
            }
            <li class="page-item@(Model.IsLast ? " disabled" : "")">
                <a class="page-link" href="@(Model.IsLast
                    ? "javascript:void(0)"
                    : Shared.GetPagingUrl(Model.Page.Value + 1))">&gt;</a>
            </li>
            <li class="page-item@(Model.IsLast ? " disabled" : "")">
                <a class="page-link" href="@(Model.IsLast
                    ? "javascript:void(0)"
                    : Shared.GetPagingUrl(Model.LastPage.Value))">&gt;&gt;</a>
            </li>
        </ul>
    </nav>
}
else
{
    <h3>查無資料</h3>
}